- name: play1
  hosts: all
  tasks:
    - name: task1 of play 1
      ansible.builtin.debug:
       msg: "hello world"
    - name: task2 of play 1
      ansible.builtin.debug:
       msg: "hello Ansible playbooks"
        